### PR TITLE
Tron TransactionBuilder: Improve validation during transaction parsing

### PR DESCRIPTION
**Pull request by JackyW47**
## Description

This pull request is to address the issue proposed in #34 . Changes are as follows:

* Added validation logic in `TransactionBuilder.fromImplementation`
* Fixed related test case - Now if a `rawTransaction` is invalid, error will be thrown during `txBuilder.from`

## Things to note

Currently the unit test is not complete. It has not covered the case that raw_data does not equal to raw_data_hex since prerequisite #46 is still under review. Will implement another negative test after #46 is merged to master.

### CODE REVIEW

**Comment by cooncesean** [comment]
@JackyW47 thanks for submitting this change request 👍 

The team is working to land #46 as we speak (the feedback loop on this has been a little longer than we'd like at the moment). Once that gets merged, feel free to rebase into your branch and add the coverage you referenced in the PR body.

More importantly, this looks great -- we love the approach and are excited to move forward to next steps.

I'll hit back on this thread once #46 has been merged.

**Comment by cooncesean** [comment]
Oh - and you're going to need to sign these commits (something we require being a crypto + fintech company focused on security).

Some notes:

* https://help.github.com/en/github/authenticating-to-github/about-commit-signature-verification
* https://help.github.com/en/github/authenticating-to-github/signing-commits

**Comment by cooncesean** [comment]
#46 was just merged.

**Comment by jwangdx** [comment]
> #46 was just merged.

Thanks for the update, and the PR has merged the latest master. No additional test cases is needed since it's already implemented in @leviathan-mist code and the test cases seem complete to me. Also, there is just a small issue that we can optimize which is proposed in issue #49 . Please take a look if you have time. Thank you!

**Comment by argjv** [comment]
This is already implemented in `validateRawTransaction()` and called right before `fromImplementation` in `BaseTransactionBuilder.ts`:

```
from(rawTransaction: any): void {
  this.validateRawTransaction(rawTransaction);
  this.transaction = this.fromImplementation(rawTransaction);
}
```

The TODO was redundant, sorry :/

**Pull request closed without merging**
